### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stephen-cisler** [stephen-cisler/springboot-blog#8]
- [ ] remove junk classes
- [ ] add dates for creation and modifications
- [ ] add custom tags for posts for sorting feature
- [ ] sort by tag
